UDOO VISION documentation
UDOOboard/Vision-Docs pull request #1
Opened 2022-08-29 14:50 UTC by dima91

2022-08-29 15:48 UTC, ektor5 requested changes
First review

2022-08-29 15:48 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +Thanks to the embedded Intel&reg; HD Graphics 500 GPU, you can use all the OpenVINO&trade; toolkit to build prrojects which leverage the AI powerful.
the AI powerful -> the power of AI

2022-08-29 15:48 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +Thanks to the embedded Intel&reg; HD Graphics 500 GPU, you can use all the OpenVINO&trade; toolkit to build prrojects which leverage the AI powerful.
`s/prroject/project/`

2022-08-29 15:48 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +**UDOO VISION** is the New PC: the most powerful maker board ever and an Arduino&trade; Leonardo-compatible platform, all embedded on the same board.
most powerful?

2022-08-29 15:48 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +Visit the [**Get Started Vision**](https://www.udoo.org/get-started-vision/) section of the UDOO website to find video tutorials of how to start use the UDOO Vision board.
`s/of how to start use the/to start using your new/`

2022-08-29 15:48 UTC, ektor5 commented on docs/02_Hardware_References/00_Overview.md
> +<span class="label label-warning">Heads up!</span> The communications between the Apollo Lake SoC and the Microchip ATmega32U4 module comes through a USB interface, exactly like an Arduino&trade; Leo
`s/communications/communication/`

2022-08-29 15:48 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Depending on the [chosen model](!Hardware_References/Board_versions) of UDOO VISION you could have an embedded multi media card memory up to 64GB to install your favorite OS.
`s/you could have an embedded multi media card/, your board may be equipped with an eMMC storage/`

2022-08-29 15:48 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Both Apollo Lake E3940 and E39050 processors embed a SATA Controller, which offers up to two **SATA III 6.0 Gbps** interfaces.
`s/E39050/E3950/`

2022-08-29 15:48 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +A dedicated power connector (*CN10*), can be used to give supply to *2.5"* Hard Disk Drives (or Solid State Drives) connected to the SATA male connector.
`s/to give supply/to power`

2022-08-29 15:48 UTC, ektor5 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +It is possible to increase the connectivity of the UDOO Vision board by using M.2 Socket 1 Key E connectivity modules (i.e. modules with functionalities like WiFi + Bluetooth).
`s/i.e. modules with functionalities like WiFi + Bluetooth /e.g., WiFi+Bluetooth module/`

2022-08-29 15:48 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +**TODO**
?

2022-08-29 15:48 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +### M.2 Wi-Fi Intel dual band ac Wi-Fi + BT 4.2 5GHz + adhesive antenna
double Wi-fi

2022-08-29 15:48 UTC, ektor5 commented on docs/03_Operating_Systems/01_Linux.md
> +In the [Getting Started](**TODO: insert correct link**) section you can find a guide of how to install a Linux distro, the example is based on the Ubuntu OS.
TODO

2022-08-29 15:48 UTC, ektor5 commented on docs/03_Operating_Systems/01_Linux.md
> +* [**Ubuntu**](https://www.ubuntu.com/): is probably the most well-known Linux distribution. Ubuntu is based on Debian, but it has its own software repositories. Much of the software in these reposit
`s/20.03/20.04/`

2022-08-29 15:48 UTC, ektor5 commented on docs/03_Operating_Systems/02_Windows.md
> +In the [Getting Started](**TODO: insert correct link**) section you can find a guide of how to install Windows, the example is based on Windows® 10 64-bit.
TODO

2022-08-29 15:48 UTC, ektor5 commented on docs/04_Basic_Setup/01_Find_IP_Address.md
>  You'll find UDOO Vision connected through the GB Ethernet identified as `Seco`.
I think it will only if connected via ethernet. Wifi has usually an Intel (or the module manufacturer) MAC.

2022-08-29 15:48 UTC, ektor5 commented on docs/04_Basic_Setup/03_Remote_Terminal_(SSH).md
> +When the connection succeeds, a black window will appear. That is the terminal.\\
Trailing '\\\\'

2022-08-29 15:48 UTC, ektor5 commented on docs/04_Basic_Setup/03_Remote_Terminal_(SSH).md
>      <username>@<IPAddres>'s password:
`s/IPAddres/IPAddress/`

2022-08-29 15:48 UTC, ektor5 commented on docs/07_Cookbook_Linux/02_OpenVINO_toolkit_installation.md
> +wget -c https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021
`curl URL | sudo apt-key add -`

2022-08-29 15:48 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/01_Overview.md
> +UDOO Vision embeds a **Microchip ATmega32u4** microcontroller, the same as Arduino&reg; Leonardo, with the same open-source schematic.
`s/Vision/VISION/`

2022-08-29 15:48 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/02_Getting_Started_with_Arduino_Leonardo.md
> +To start programming the Arduino&reg; Leonardo-compatible embedded microcontroller of the UDOO Vision you need the `Arduino IDE` or the `Arduino Web IDE`.
ditto

2022-08-29 15:48 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/02_Getting_Started_with_Arduino_Leonardo.md
> +If you have issues when trying to upload a sketch on the Arduino Leonardo-compatible ATmega32U4 of UDOO Vision you probably have a conflict with the program **ModemManager** (installed by default on
ditto

2022-08-29 15:48 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/02_Getting_Started_with_Arduino_Leonardo.md
> +Since you probably don't have a modem on your UDOO Vision you can safely uninstall the package to solve the issue or disable it running the commands:
In the beginning it was all uppercase, now lowercase. What's the official naming?

2022-08-29 15:48 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/03_Pinout.md
> +**TODO FIXME: add correct image**<!--<a href="../img/x86ii_pinout_arduino.png" target="_blank"><img style="width:600px; " src="../img/x86ii_pinout_arduino.png"></a>_-->
TODO

2022-08-29 15:48 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/03_Pinout.md
>  UDOO Vision Arduino Leonardo side is compatible with all the shield supported by the original Arduino Leonardo.
How?

2022-08-29 15:48 UTC, ektor5 commented on docs/13_Advanced_Topics/02_EAPI.md
> +Windows and Linux, even if it is not completely tested.
>even if it is not completely tested.

What is working?

2022-08-30 12:37 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> +Thanks to the embedded Intel&reg; HD Graphics 500 GPU, you can use all the OpenVINO&trade; toolkit to build prrojects which leverage the AI powerful.
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:38 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> +Visit the [**Get Started Vision**](https://www.udoo.org/get-started-vision/) section of the UDOO website to find video tutorials of how to start use the UDOO Vision board.
Solved in fa92ed745fbe1730caab584eb0604e5c2260ec2a

2022-08-30 12:39 UTC, dima91 commented on docs/02_Hardware_References/00_Overview.md
> +<span class="label label-warning">Heads up!</span> The communications between the Apollo Lake SoC and the Microchip ATmega32U4 module comes through a USB interface, exactly like an Arduino&trade; Leo
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:39 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Depending on the [chosen model](!Hardware_References/Board_versions) of UDOO VISION you could have an embedded multi media card memory up to 64GB to install your favorite OS.
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:40 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Both Apollo Lake E3940 and E39050 processors embed a SATA Controller, which offers up to two **SATA III 6.0 Gbps** interfaces.
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:40 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +A dedicated power connector (*CN10*), can be used to give supply to *2.5"* Hard Disk Drives (or Solid State Drives) connected to the SATA male connector.
Solved in 2642a9c115bebd56b25423773ad612de3ee187b5

2022-08-30 12:41 UTC, dima91 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +It is possible to increase the connectivity of the UDOO Vision board by using M.2 Socket 1 Key E connectivity modules (i.e. modules with functionalities like WiFi + Bluetooth).
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:41 UTC, dima91 commented on docs/03_Operating_Systems/01_Linux.md
> +In the [Getting Started](**TODO: insert correct link**) section you can find a guide of how to install a Linux distro, the example is based on the Ubuntu OS.
Solved in fa92ed745fbe1730caab584eb0604e5c2260ec2a

2022-08-30 12:42 UTC, dima91 commented on docs/03_Operating_Systems/01_Linux.md
> +* [**Ubuntu**](https://www.ubuntu.com/): is probably the most well-known Linux distribution. Ubuntu is based on Debian, but it has its own software repositories. Much of the software in these reposit
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:46 UTC, dima91 commented on docs/03_Operating_Systems/02_Windows.md
> +In the [Getting Started](**TODO: insert correct link**) section you can find a guide of how to install Windows, the example is based on Windows® 10 64-bit.
Solved in fa92ed745fbe1730caab584eb0604e5c2260ec2a

2022-08-30 12:48 UTC, dima91 commented on docs/04_Basic_Setup/03_Remote_Terminal_(SSH).md
> +When the connection succeeds, a black window will appear. That is the terminal.\\
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:48 UTC, dima91 commented on docs/04_Basic_Setup/03_Remote_Terminal_(SSH).md
>      <username>@<IPAddres>'s password:
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:49 UTC, dima91 commented on docs/13_Advanced_Topics/02_EAPI.md
> +Windows and Linux, even if it is not completely tested.
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:51 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/03_Pinout.md
>  UDOO Vision Arduino Leonardo side is compatible with all the shield supported by the original Arduino Leonardo.
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:51 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/03_Pinout.md
> +**TODO FIXME: add correct image**<!--<a href="../img/x86ii_pinout_arduino.png" target="_blank"><img style="width:600px; " src="../img/x86ii_pinout_arduino.png"></a>_-->
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:52 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/02_Getting_Started_with_Arduino_Leonardo.md
> +Since you probably don't have a modem on your UDOO Vision you can safely uninstall the package to solve the issue or disable it running the commands:
Solved in fa92ed745fbe1730caab584eb0604e5c2260ec2a

2022-08-30 12:52 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/02_Getting_Started_with_Arduino_Leonardo.md
> +If you have issues when trying to upload a sketch on the Arduino Leonardo-compatible ATmega32U4 of UDOO Vision you probably have a conflict with the program **ModemManager** (installed by default on
Solved in fa92ed745fbe1730caab584eb0604e5c2260ec2a

2022-08-30 12:52 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/01_Overview.md
> +UDOO Vision embeds a **Microchip ATmega32u4** microcontroller, the same as Arduino&reg; Leonardo, with the same open-source schematic.
Solved in fa92ed745fbe1730caab584eb0604e5c2260ec2a

2022-08-30 12:53 UTC, dima91 commented on docs/07_Cookbook_Linux/02_OpenVINO_toolkit_installation.md
> +wget -c https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-30 12:54 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/02_Getting_Started_with_Arduino_Leonardo.md
> +To start programming the Arduino&reg; Leonardo-compatible embedded microcontroller of the UDOO Vision you need the `Arduino IDE` or the `Arduino Web IDE`.
Solved in 18f7d56e113b578bf5ddee73af70e9741905eb4f

2022-08-31 07:33 UTC, ektor5 requested changes
Second review

2022-08-31 07:33 UTC, ektor5 commented on docs/02_Hardware_References/01_Resources.md
>  * [Bill of Material (BOM)](coming soon)
TODO

2022-08-31 07:33 UTC, ektor5 commented on docs/04_Basic_Setup/01_Find_IP_Address.md
>  ## Third method: use your Router’s control panel
`s/Router’s/Router/`

2022-08-31 07:33 UTC, ektor5 commented on docs/07_Cookbook_Linux/02_OpenVINO_toolkit_installation.md
>  sudo echo "deb https://apt.repos.intel.com/openvino/2021 all main" | tee /etc/apt/sources.list.d/intel-openvino-2021.list
Superuser privileges are needed for `tee` not `echo`.
`echo foo | sudo tee file`

2022-08-31 07:33 UTC, ektor5 commented on docs/13_Advanced_Topics/02_EAPI.md
> +an official version until now but we are working to provide you a stable and tested release.
`s/until/by/` or "at the time of writing"

2022-08-31 10:57 UTC, ektor5 requested changes, later dismissed
missing file

2022-08-31 14:28 UTC, ektor5 requested changes

2022-08-31 14:28 UTC, ektor5 commented on docs/02_Hardware_References/02_Board_versions.md
> +| Storage eMMC | 64GB eMMC storage                            | 64GB eMMC storage                            |
Is the same emmc size in the two versions? In the introduction it says that X5 has 32GB

2022-08-31 14:28 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Depending on the [chosen model](!Hardware_References/Board_versions) of UDOO VISION, your board may be equipped with an eMMC storage memory up to 64GB to install your favorite OS.
There is a version without eMMC? If not `s/may be/is`

2022-08-31 14:28 UTC, ektor5 commented on docs/02_Hardware_References/03_Video_Output.md
> +* Intel&reg; HD Graphics 405 Up to 700 MHz 16 execution units (**ULTRA** version)
ULTRA? Seems like these two lines are not correct

2022-08-31 14:28 UTC, ektor5 commented on docs/02_Hardware_References/03_Video_Output.md
> +i.e. it can be used to support DP displays directly and, through an external adapter, also HDMI or DVI displays.
`s/, i.e. it/. It/`

2022-08-31 14:28 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Of these interfaces, one SATA channel is carried out to a standard male S-ATA connector, CN11 (the other SATA channel is available on the M.2 Key B socket).
Is SATA or S-ATA? Feels confusing

2022-08-31 14:28 UTC, ektor5 commented on docs/02_Hardware_References/03_Video_Output.md
> +### UDOO VISION Hardware and UEFI BIOS User Manual
This doesn't belong in a Video Output section.

2022-08-31 14:46 UTC, ektor5 requested changes

2022-08-31 14:46 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +The UDOO VISION, for those who bought the board fro mthe Kickstarter campaign, is sold with a metal case to be placed on the top part of your board.
typo

2022-08-31 14:46 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +You'll need it to protect your board from external damages!
It protects your board from accidental damages and makes it better looking on your desk. 
(or rewrite it better)

2022-08-31 14:46 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +Soon it will also be available on the [official shop](https://shop.udoo.org/), to be able to buy a new board together.
Please rewrite. It is not clear if you can buy the board with the case pre-mounted.  
Otherwise just say: "It will be available soon in the [official shop](https://shop.udoo.org/)".

2022-08-31 14:46 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +The UDOO VISION, for those who bought the board fro mthe Kickstarter campaign, is sold with a metal case to be placed on the top part of your board.
On kickstarter you don't sell products, it's a "reward". You don't buy, you "back the project".

2022-08-31 14:52 UTC, ektor5 requested changes
missing file

2022-08-31 14:52 UTC, ektor5 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/03_Pinout.md
> +<a href="../img/udoo_vision_arduino_pinout.jpg" target="\_blank"><img style="width:700px; " src="../img/udoo_vision_arduino_pinout.jpg" alt="UDOO VISION Arduino pinout"></a>
missing file

2022-08-31 15:00 UTC, ektor5 requested changes

2022-08-31 15:00 UTC, ektor5 commented on docs/02_Hardware_References/03_Video_Output.md
> +On the UDOO VISION board, the Digital Display Interfaces #0 used to implement a multimode Display Port (DP++) interface,
`s/used to implement/is/` or `s/used to implement/implements/`

2022-08-31 15:00 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +The SoCs used on UDOO VISION module offer a **SD/MMC 4.0** compliant interface, that can be used as a boot device and/or to implement another mass storages media other than the optional internal eMMC
`s/implement/add`

2022-08-31 15:00 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +The SoCs used on UDOO VISION module offer a **SD/MMC 4.0** compliant interface, that can be used as a boot device and/or to implement another mass storages media other than the optional internal eMMC
Why is the eMMC is "optional"?

2022-08-31 15:25 UTC, ektor5 requested changes

2022-08-31 15:25 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
>  If you have any <b>trouble</b> uploading the <b>Arduino sketch</b> running Linux, check the <i>Linux Known issue - Sketch upload</i> section in the <a href="../Arduino_Leonardo-compatible(ATmega32U4)
Not found. Switch to `[quote](link)` style

2022-08-31 15:25 UTC, ektor5 commented on docs/02_Hardware_References/00_Overview.md
> +| <img src="../img/icons/mass-storage.png" height="20px" width="20px"> | Mass Storage     | eMMC disk up to 64 GB soldered on board, dtandard SATA connector, M.2 Key B SSD slot, Micro SD card slot |
typo

2022-08-31 15:25 UTC, ektor5 commented on docs/02_Hardware_References/00_Overview.md
> +| <img src="../img/icons/os.png" height="20px" width="20px">           | Operating System | Windows 10, 8.1, 7 64bit, any Linux Distribution 64bit platform |
`s/any Linux Distribution 64bit platform/Linux/`

2022-08-31 15:25 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +To mount the WiFi/BT Kit is necessary the following fixtures (not included with the item):
Ditto.

2022-08-31 15:25 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +To mount the SSD is necessary the following fixtures (not included with the item):
Are they necessary on UDOO VISION?

2022-08-31 15:27 UTC, ektor5 requested changes

2022-08-31 15:27 UTC, ektor5 commented on docs/13_Advanced_Topics/02_EAPI.md
> +such as SBCs. Read the full specification [here][https://www.picmg.org/wp-content/uploads/COM_EAPI_R1_0.pdf].
Switch to style `[quote](link)`

2022-10-10 13:37 UTC, dima91 commented on docs/04_Basic_Setup/01_Find_IP_Address.md
>  ## Third method: use your Router’s control panel
Fixed with 97dd556

2022-10-10 13:38 UTC, dima91 commented on docs/07_Cookbook_Linux/02_OpenVINO_toolkit_installation.md
>  sudo echo "deb https://apt.repos.intel.com/openvino/2021 all main" | tee /etc/apt/sources.list.d/intel-openvino-2021.list
Fixed with 97dd556

2022-10-10 13:38 UTC, dima91 commented on docs/13_Advanced_Topics/02_EAPI.md
> +an official version until now but we are working to provide you a stable and tested release.
Fixed with 97dd556

2022-10-10 13:38 UTC, dima91 commented on docs/02_Hardware_References/02_Board_versions.md
> +| Storage eMMC | 64GB eMMC storage                            | 64GB eMMC storage                            |
Fixed with 97dd556

2022-10-10 13:38 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Depending on the [chosen model](!Hardware_References/Board_versions) of UDOO VISION, your board may be equipped with an eMMC storage memory up to 64GB to install your favorite OS.
Fixed with 97dd556

2022-10-10 13:38 UTC, dima91 commented on docs/02_Hardware_References/03_Video_Output.md
> +* Intel&reg; HD Graphics 405 Up to 700 MHz 16 execution units (**ULTRA** version)
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/02_Hardware_References/03_Video_Output.md
> +i.e. it can be used to support DP displays directly and, through an external adapter, also HDMI or DVI displays.
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/02_Hardware_References/03_Video_Output.md
> +### UDOO VISION Hardware and UEFI BIOS User Manual
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +The UDOO VISION, for those who bought the board fro mthe Kickstarter campaign, is sold with a metal case to be placed on the top part of your board.
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +You'll need it to protect your board from external damages!
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +Soon it will also be available on the [official shop](https://shop.udoo.org/), to be able to buy a new board together.
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +The UDOO VISION, for those who bought the board fro mthe Kickstarter campaign, is sold with a metal case to be placed on the top part of your board.
Fixed with 97dd556

2022-10-10 13:39 UTC, dima91 commented on docs/02_Hardware_References/03_Video_Output.md
> +On the UDOO VISION board, the Digital Display Interfaces #0 used to implement a multimode Display Port (DP++) interface,
Fixed with 97dd556

2022-10-10 13:40 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +The SoCs used on UDOO VISION module offer a **SD/MMC 4.0** compliant interface, that can be used as a boot device and/or to implement another mass storages media other than the optional internal eMMC
Fixed with 97dd556

2022-10-10 13:40 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
>  If you have any <b>trouble</b> uploading the <b>Arduino sketch</b> running Linux, check the <i>Linux Known issue - Sketch upload</i> section in the <a href="../Arduino_Leonardo-compatible(ATmega32U4)
Fixed with 97dd556

2022-10-10 13:40 UTC, dima91 commented on docs/02_Hardware_References/00_Overview.md
> +| <img src="../img/icons/mass-storage.png" height="20px" width="20px"> | Mass Storage     | eMMC disk up to 64 GB soldered on board, dtandard SATA connector, M.2 Key B SSD slot, Micro SD card slot |
Fixed with 97dd556

2022-10-10 13:40 UTC, dima91 commented on docs/02_Hardware_References/00_Overview.md
> +| <img src="../img/icons/os.png" height="20px" width="20px">           | Operating System | Windows 10, 8.1, 7 64bit, any Linux Distribution 64bit platform |
Fixed with 97dd556

2022-10-10 13:40 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +To mount the WiFi/BT Kit is necessary the following fixtures (not included with the item):
Fixed with 97dd556

2022-10-10 13:40 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +To mount the SSD is necessary the following fixtures (not included with the item):
Fixed with 97dd556

2022-10-10 13:41 UTC, dima91 commented on docs/13_Advanced_Topics/02_EAPI.md
> +such as SBCs. Read the full specification [here][https://www.picmg.org/wp-content/uploads/COM_EAPI_R1_0.pdf].
Fixed with 97dd556

2022-10-10 13:41 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +The SoCs used on UDOO VISION module offer a **SD/MMC 4.0** compliant interface, that can be used as a boot device and/or to implement another mass storages media other than the optional internal eMMC
Fixed with 97dd556

2022-10-10 13:41 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +Of these interfaces, one SATA channel is carried out to a standard male S-ATA connector, CN11 (the other SATA channel is available on the M.2 Key B socket).
Fixed with 97dd556

2022-10-10 14:05 UTC, dima91 commented on docs/08_Arduino_Leonardo-compatible(ATmega32U4)/03_Pinout.md
> +<a href="../img/udoo_vision_arduino_pinout.jpg" target="\_blank"><img style="width:700px; " src="../img/udoo_vision_arduino_pinout.jpg" alt="UDOO VISION Arduino pinout"></a>
Solved with 175e1b7

2022-10-11 15:49 UTC, ektor5 requested changes
second pass

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +**UDOO VISION** is the New PC: the most powerful maker board ever and an Arduino&trade; Leonardo-compatible platform, all embedded on the same board.
.

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +Download the [**User Manual**](https://udoo.org/download/files/UDOO_VISION/Doc/UDOO_VISION_MANUAL.pdf) to have more complete explanation of the UDOO VISION hardware.
TODO

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +Download the [**User Manual**](https://udoo.org/download/files/UDOO_VISION/Doc/UDOO_VISION_MANUAL.pdf) to have more complete explanation of the UDOO VISION hardware.
`s/to have more/to have a more/`

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +* Do not use a *NON*-standard USB 3.0 peripheral. If you use a non-standard USB 3.0 peripheral with an external power plug, this could send back the power source to the UDOO VISION board with the ris
`s/back the power source/current back/`

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> + * [Facebook page](http://www.facebook.com/udooboard)
use https

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/03_Video_Output.md
> +On the boottom side of UDDO VISION is located the embedded Display Port connector.
`s/boottom/bottom/`

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +<span class="label label-warning">Heads up!</span> As a flash-based storage device, excessive drive access, particularly write commands, reduces its useful life. Therefore, it is strongly suggested t
`s/useful//`

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +The mass storage capabilities of the UDOO VISION are completed by an M.2 SSD Slot, which allow plugging **M.2 Socket 2 Key B** Solid State Drives with *SATA* interface.
`s/allow/allows/`

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/04_Storage_Options.md
> +For the additional informations about M.2 connectors, look at the [relative section](Hardware_References/M.2_Connectors).
`s/For the/For`

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +The mass storage capabilities of the UDOO VISION are completed by an M.2 SSD Slot, which allow plugging M.2 Socket 2 Key B Solid State Drives with SATA interface.
`s/allow/allows/`

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +On this socket, il also possible to connect a WWAN module in 2260 or 3042 size. It allow you to connect to a cellular network using the connected SIM slot *CN13*.
`s/il/is`

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +On this socket, il also possible to connect a WWAN module in 2260 or 3042 size. It allow you to connect to a cellular network using the connected SIM slot *CN13*.
`s/allow/allows/`

2022-10-11 15:49 UTC, ektor5 commented on docs/03_Accessories/01_Official_Accessories.md
> +The UDOO VISION, for those who backed the project from the Kickstarter campaign, is sold with a metal case to be placed on the top part of your board.
check

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +While the Apollo Lake processor can run all the Windows and Linux 64bit distros you want to use as desktop PC, the ATmega32U4 allows easy access to a Arduino&trade; Leonardo environment.
`s/a Arduino/an Arduino/`

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
>   * [YouTube](http://www.youtube.com/channel/UCXv5UyGn5jArK8xOAmuSeHg)
ditto

2022-10-11 15:49 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> + * [Twitter](http://twitter.com/UDOO_Board)
ditto

2022-10-11 15:49 UTC, ektor5 commented on docs/02_Hardware_References/00_Overview.md
> +<span class="label label-warning">Heads up!</span> The communication between the Apollo Lake SoC and the Microchip ATmega32U4 module comes through a USB interface, exactly like an Arduino&trade; Leon
`s/connects/connected/`

2022-10-19 08:00 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> +Download the [**User Manual**](https://udoo.org/download/files/UDOO_VISION/Doc/UDOO_VISION_MANUAL.pdf) to have more complete explanation of the UDOO VISION hardware.
Solved with 0006c75

2022-10-19 08:00 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> +* Do not use a *NON*-standard USB 3.0 peripheral. If you use a non-standard USB 3.0 peripheral with an external power plug, this could send back the power source to the UDOO VISION board with the ris
Solved with 0006c75

2022-10-19 08:00 UTC, dima91 commented on docs/02_Hardware_References/03_Video_Output.md
> +On the boottom side of UDDO VISION is located the embedded Display Port connector.
Solved with 0006c75

2022-10-19 08:00 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +<span class="label label-warning">Heads up!</span> As a flash-based storage device, excessive drive access, particularly write commands, reduces its useful life. Therefore, it is strongly suggested t
Solved with 0006c75

2022-10-19 08:00 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +For the additional informations about M.2 connectors, look at the [relative section](Hardware_References/M.2_Connectors).
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +The mass storage capabilities of the UDOO VISION are completed by an M.2 SSD Slot, which allow plugging M.2 Socket 2 Key B Solid State Drives with SATA interface.
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/02_Hardware_References/05_M.2_Connectors.md
> +On this socket, il also possible to connect a WWAN module in 2260 or 3042 size. It allow you to connect to a cellular network using the connected SIM slot *CN13*.
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> +While the Apollo Lake processor can run all the Windows and Linux 64bit distros you want to use as desktop PC, the ATmega32U4 allows easy access to a Arduino&trade; Leonardo environment.
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> + * [Twitter](http://twitter.com/UDOO_Board)
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/02_Hardware_References/00_Overview.md
> +<span class="label label-warning">Heads up!</span> The communication between the Apollo Lake SoC and the Microchip ATmega32U4 module comes through a USB interface, exactly like an Arduino&trade; Leon
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
>   * [YouTube](http://www.youtube.com/channel/UCXv5UyGn5jArK8xOAmuSeHg)
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/02_Hardware_References/04_Storage_Options.md
> +The mass storage capabilities of the UDOO VISION are completed by an M.2 SSD Slot, which allow plugging **M.2 Socket 2 Key B** Solid State Drives with *SATA* interface.
Solved with 0006c75

2022-10-19 08:01 UTC, dima91 commented on docs/01_Introduction/00_Introduction.md
> + * [Facebook page](http://www.facebook.com/udooboard)
Solved with 0006c75

2022-10-19 10:57 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +The UDOO VISION, for those who backed the project from the Kickstarter campaign, is sold with a metal case to be placed on the top part of your board.
Solved with 03e5b0feb9addad07fda8bc5b8b4796f0a559bb2

2022-10-20 07:33 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +**TODO**
Done

2022-10-20 07:34 UTC, dima91 commented on docs/03_Accessories/01_Official_Accessories.md
> +### M.2 Wi-Fi Intel dual band ac Wi-Fi + BT 4.2 5GHz + adhesive antenna
Solved

2022-10-20 15:00 UTC, ektor5 requested changes
Broken links

2022-10-20 15:00 UTC, ektor5 commented on docs/01_Introduction/00_Introduction.md
> +Visit the [**Get Started VISION**](https://www.udoo.org/get-started-vision/) section of the UDOO website to find video tutorials to start using your new UDOO VISION board.
Broken link

2022-10-24 16:21 UTC, merged